# https://taskfile.dev
version: '3'
vars:
  BINFILE: gobadger

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  linter:
    desc: "execute linter"
    cmds:
      - golangci-lint

  binary:
    desc: "Build binary"
    cmds:
      - CGO_ENABLED=0 go build .
    #   - upx -q {{.BINFILE}}
    # # silent: true
    # method: checksum
    # generates:
    #   - "{{.BINFILE}}"

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean

  godoc:
    desc: "Run godoc server"
    cmds:
      - echo "http://localhost:6060/"
      - godoc -http=:6060
    