# https://taskfile.dev
version: '3'
vars:
  BINFILE: gobadger

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  linter:
    desc: "execute linter"
    cmds:
      - golangci-lint run

  binary:
    desc: "Build binary"
    cmds:
      - CGO_ENABLED=0 go build -o {{.BINFILE}} .

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --skip validate

  godoc:
    desc: "Run godoc server"
    cmds:
      - echo "http://localhost:6060/"
      - godoc -http=:6060

  test:
    desc: "Run all tests"
    cmds:
      - go test ./... -v

  test-coverage:
    desc: "Run tests with coverage"
    cmds:
      - go test ./... -coverprofile=profile.cov
      #- # go test ./internal/... -coverpkg=./internal/... -coverprofile=profile.cov
      #- #echo -n "Total Coverage{{":"}} "
      - go tool cover -func profile.cov | grep '^total:' | awk '{print $3}' | sed 's/%//'
      - rm -f profile.cov