name: build
on:
  push:
    branches:    
      - '*'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21.5'
    - name: Install dependencies
      run: |
        go version
        go install golang.org/x/lint/golint@latest
    - name: Build
      run: |
        go mod vendor
        go build .
    # - name: Test With Coverage
    #   run: go test -v  -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Run Vet & Lint
      run: |
        go vet .
        golint -set_exit_status=1 .
